"""initial_schema

Revision ID: 238fe5c9382a
Revises: 
Create Date: 2026-05-02 22:48:06.007030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '238fe5c9382a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use create_all so the migration is a no-op on an already-initialised DB
    # (create_all uses checkfirst=True by default via Alembic's op.create_table).
    # We delegate to SQLAlchemy metadata so we never need to hand-write every column.
    from app.database import Base, engine  # noqa
    Base.metadata.create_all(bind=engine, checkfirst=True)


def downgrade() -> None:
    from app.database import Base, engine  # noqa
    Base.metadata.drop_all(bind=engine)



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_invoices', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customer_quotations', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('customers', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'pdf_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('quotations', 'line_breakdown',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('quote_lines', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('vendors', 'catalog_items',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'catalog_items',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('quote_lines', 'channel',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quotations', 'line_breakdown',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('purchase_orders', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customers', 'logo_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_quotations', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_invoices', 'pdf_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
